<?php
$int_flags = array(
0 => 'Misc',
1 => 'Affects Status only',
2 => 'Affects Stats only',
3 => 'Heals user',
4 => 'Damage & Status',
5 => 'Status and Stats',
6 => 'Damage & Stats',
7 => 'Damage, raise stats',
8 => 'Absorb HP',
9 => 'OHKOs target',
10 => 'Affects everyone',
11 => 'Affects single party',
12 => 'Forces Switch',
13 => 'Gimmick',
);

$status = array(
0 => 'None',
1 => 'Paralysis',
2 => 'Sleep',
3 => 'Freeze',
4 => 'Burn',
5 => 'Poison',
6 => 'Confusion',
7 => 'Infatuation',
8 => 'Trap',
9 => 'Nightmare',
10 => '10',
11 => '11',
12 => 'Torment',
13 => 'Disable',
14 => 'Next-turn sleep',
15 => 'No Healing',
16 => '16',
17 => 'Foresight',
18 => 'Leech Seed',
19 => 'Cannot use item',
20 => 'Perish Song',
21 => 'Ingrain',
255 => '255'
);
$evolutiontypes = array(
0 => 'does not evolve.',
1 => 'evolves into %2$s with maximum happiness',
2 => 'evolves into %2$s with max happiness in the daytime',
3 => 'evolves into %2$s with max happiness in the nighttime',
4 => 'evolves into %2$s at level %1$u',
5 => 'evolves into %2$s when traded',
6 => 'evolves into %2$s with traded holding %1$s',
7 => 'evolves into %2$s when traded for ???',
8 => 'evolves into %2$s when exposed to %1$s',
9  => 'evolves into %2$s with attack > defense at level %1$u',
10 => 'evolves into %2$s with attack = defense at level %1$u',
11 => 'evolves into %2$s with attack < defense at level %1$u',
12 => 'evolves into %2$s if personality < 5 at level %1$u',
13 => 'evolves into %2$s if personality > 4 at level %1$u',
14 => 'evolves into %2$s at level %1$u...',
15 => 'evolves into %2$s if space is in party',
16 => 'evolves into %2$s when levelled up while Beauty > %1$u',
17 => 'evolves into %2$s when %1$s is used and is male',
18 => 'evolves into %2$s when %1$s is used and is female',
19 => 'evolves into %2$s when holding %1$s in the day',
20 => 'evolves into %2$s when holding %1$s at night',
21 => 'evolves into %2$s when %1$s is learned',
22 => 'evolves into %2$s with %1$s in party',
23 => 'evolves into %2$s at level %1$u if male',
24 => 'evolves into %2$s at level %1$u if female',
25 => 'evolves into %2$s when levelled up in Chargestone Cave',
26 => 'evolves into %2$s when levelled up at a Mossy Rock',
27 => 'evolves into %2$s when levelled up near an Ice Rock',
);

$stats = array(
0 => 'None',
1 => 'Attack',
2 => 'Defence',
3 => 'Sp. Atk',
4 => 'Sp. Def',
5 => 'Speed',
6 => 'Accuracy',
7 => 'Evasiveness',
8 => 'Everything'
);
?>